---
title: "Trabajo Práctico 2 | Grupo 2" 
date: "r Sys.Date()" # Inserta la fecha automáticamente 
format: html
theme: Cosmo 
toc: true 
toc-location: right 
number-sections: true 
code-fold: true # Permitir plegado de bloques de código 
code-tools: true # Mostrar herramientas de copiado en los bloques de código 
smooth-scroll: true # Habilitar desplazamiento suave al navegar por el índice 
fig-align: center # Alinear las figuras al centro 
toc-depth: 3 # Profundidad máxima del índice 
lang: es # Establecer idioma del documento 
editor: visual # Editor visual habilitado
---

# Trabajo Práctico 2

Análisis Exploratorio de Datos de un Dataset Real

```{r}
library(dplyr)
datos <- readRDS("data/datos_smn.rds")
estaciones <- read.csv("data/estaciones.csv")
precipitaciones <- read.delim("data/smn_precipitaciones-1991-2024.txt", sep = ",")

join_1 <- estaciones %>% 
  inner_join(datos, by = c("Nombre" = "NOMBRE"))
precipitaciones$Fecha <-  as.Date(precipitaciones$Fecha, format = "%Y-%m-%d")
dataset <- join_1 %>%
  inner_join(precipitaciones, by = c("Nro" = "Estacion", "FECHA" = "Fecha"))

dataset$Precipitacion..mm. <- as.numeric(dataset$Precipitacion..mm.) 
```

#Ver datos faltantes por columnas

```{r}
# Verificar valores nulos
na_count <- sapply(dataset, function(x) sum(is.na(x)))
print(na_count)

# Visualizar un mapa de calor de valores faltantes (requiere la librería VIM)
# install.packages("VIM")
library(VIM)
aggr(dataset, col = c('navyblue','red'), numbers = TRUE, sortVars = TRUE, labels = names(data), cex.axis = .7, gap = 3, ylab = c("Histograma de NAs","Patrón de NAs"))
```

#Con este código, se pueden visualizar columnas con muchos NAs. Por ejemplo la variable PNM, la cual muestra la presión atmosférica, contiene 88110 NAs y valores atípicos e imposibles en la superficie terrestre como una presión atmosférica de 3000 hPa o 100 hPa

```{r}

# Suponiendo que tu dataset se llama 'datos'
# Filtramos eliminando NA y restringiendo los valores al rango deseado
df_filter <- dataset %>%
  na.omit() %>%  # Eliminar filas con NA
  filter(
    PNM >= 950 & PNM <= 1050,
    HUM >= 0 & HUM <= 100,
    FF >= 0 & FF <= 150,
    DD >= 0 & DD <= 360,
    TEMP >= -35 & TEMP <= 50
  )

# Ver los primeros resultados para verificar
head(df_filter)


```

